#!/usr/bin/env bash

a=$(lscpu | awk -F '/Thread\(s\) per core/ { print $2 }' | xargs )
b=$(lscpu | awk -F '/Core\(s\) per socket/ { print $2 }' | xargs )

c=$(awk '/MemTotal:/ {print $2}' /proc/meminfo) # in KiB
d=$(awk '/SwapTotal:/ {print $2}' /proc/meminfo) # in KiB

e=$(($c/1000000))
f=$(($e*1024)) # total ram in GiB (including swap??)

g=$(($d/1000000))
h=$(($g*1024)) #total swap in GiB
i=$(($f-$h))


printf "---- General ----"
printf "Distro\t| %s\n " "$(grep -w 'PRETTY_NAME=' /etc/os-release | cut -d= -f2 | tr -d '"')"
printf "Kernel\t| %s\n" "$(uname -rs)"
printf "Uptime\t| %s\n" "$(uptime -p | xargs)"
printf "Mobo\t| %s\n" "$(cat /sys/devices/virtual/dmi/id/board_{vendor,name,version} | xargs)"

printf "\n---- CPU ----"
printf "Model\t| %s\n" "$(lscpu | grep -w "Model name:" | cut -c13- | xargs)"
printf "Speed\t| %s\n" "$(lscpu | grep -w "CPU max MHz" | cut -c14- | xargs)"
printf "Cores\t| %s\n"  "$b"
printf 'Threads\t| %s\n' "$(($a*$b))" 
echo
echo "---- GPU ----"
echo -e 'GPU\t| ' $(lspci -m | grep 'VGA' | cut -d '"' -f6)
echo
echo "---- RAM ----"
echo -e 'Memory\t| ' $(($f/1000))" GiB"
echo -e 'Swap\t| ' $(($h/1000))" GiB" 
